D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\custreturnsmergeupdate.php"

D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\ordershippedcompletemergeupdate.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\salesplan_update.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\salesplan_desc_update.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\fillratemergeupdate.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\linesbybilltoshipto.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\IM0011_FRissues.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\delivery_dates.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\whslines_shipqty_update.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\massalgorithm_skuopt.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\massalgorithm_damage.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\massalgorithm_shipacc.php"

REM d:\php\php.exe "D:\xampp\htdocs\MySQLUpdates\customerscoresbybillto.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\customerscores_SALESPLAN.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\customerscores_BILLTO.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\customerscores_SHIPTO.php"
D:\xampp\php\php.exe "D:\xampp\htdocs\MySQLUpdates\customerscores_CUSTOMGROUP.php"
